/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as ConsultingIndexRouteImport } from './routes/consulting/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as TagsTagRouteImport } from './routes/tags/$tag'
import { Route as PostsSplatRouteImport } from './routes/posts/$'
import { Route as PostsPagePageRouteImport } from './routes/posts/page/$page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingIndexRoute = ConsultingIndexRouteImport.update({
  id: '/consulting/',
  path: '/consulting/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSplatRoute = PostsSplatRouteImport.update({
  id: '/posts/$',
  path: '/posts/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPagePageRoute = PostsPagePageRouteImport.update({
  id: '/posts/page/$page',
  path: '/posts/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/$': typeof PostsSplatRoute
  '/tags/$tag': typeof TagsTagRoute
  '/about/': typeof AboutIndexRoute
  '/consulting/': typeof ConsultingIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/posts/page/$page': typeof PostsPagePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$': typeof PostsSplatRoute
  '/tags/$tag': typeof TagsTagRoute
  '/about': typeof AboutIndexRoute
  '/consulting': typeof ConsultingIndexRoute
  '/contact': typeof ContactIndexRoute
  '/posts': typeof PostsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/series': typeof SeriesIndexRoute
  '/tags': typeof TagsIndexRoute
  '/posts/page/$page': typeof PostsPagePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts/$': typeof PostsSplatRoute
  '/tags/$tag': typeof TagsTagRoute
  '/about/': typeof AboutIndexRoute
  '/consulting/': typeof ConsultingIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/posts/page/$page': typeof PostsPagePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts/$'
    | '/tags/$tag'
    | '/about/'
    | '/consulting/'
    | '/contact/'
    | '/posts/'
    | '/projects/'
    | '/series/'
    | '/tags/'
    | '/posts/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts/$'
    | '/tags/$tag'
    | '/about'
    | '/consulting'
    | '/contact'
    | '/posts'
    | '/projects'
    | '/series'
    | '/tags'
    | '/posts/page/$page'
  id:
    | '__root__'
    | '/'
    | '/posts/$'
    | '/tags/$tag'
    | '/about/'
    | '/consulting/'
    | '/contact/'
    | '/posts/'
    | '/projects/'
    | '/series/'
    | '/tags/'
    | '/posts/page/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsSplatRoute: typeof PostsSplatRoute
  TagsTagRoute: typeof TagsTagRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ConsultingIndexRoute: typeof ConsultingIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  PostsPagePageRoute: typeof PostsPagePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting/': {
      id: '/consulting/'
      path: '/consulting'
      fullPath: '/consulting/'
      preLoaderRoute: typeof ConsultingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$': {
      id: '/posts/$'
      path: '/posts/$'
      fullPath: '/posts/$'
      preLoaderRoute: typeof PostsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/page/$page': {
      id: '/posts/page/$page'
      path: '/posts/page/$page'
      fullPath: '/posts/page/$page'
      preLoaderRoute: typeof PostsPagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsSplatRoute: PostsSplatRoute,
  TagsTagRoute: TagsTagRoute,
  AboutIndexRoute: AboutIndexRoute,
  ConsultingIndexRoute: ConsultingIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  PostsPagePageRoute: PostsPagePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
